# a note on naming conventions ####

# R objects and scripts = snake_case
# data files generated by R dataloaders = kebab-case
# JS code = camelCase

# it makes perfect sense to me...

# frequently used libraries ####

#library(knitr)
#library(kableExtra)

library(readxl) 
#library(writexl)

library(jsonlite)
library(janitor)
library(scales)
library(glue)

library(tidytext)

# this isn't going on GH so let's just load tidyverse.
library(tidyverse)
#library(dplyr)
#library(tidyr)
#library(readr)
#library(tibble)
#library(stringr)
#library(purrr)

#library(lubridate)

## moved BN-specific code to bn.R; add path to the data loaders.